pub const LOREM: &[u8] = concat!(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ",
    "ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ",
    "ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in ",
    "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur ",
    "sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est ",
    "laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium ",
    "doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et ",
    "quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia ",
    "voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ",
    "ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor ",
    "sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut ",
    "labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum ",
    "exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. ",
    "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae ",
    "consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. At vero eos et ",
    "accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti ",
    "atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non ",
    "provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et ",
    "dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, ",
    "cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat ",
    "facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem ",
    "quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates ",
    "repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente ",
    "delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus ",
    "asperiores repellat. Hanc ego cum teneam sententiam, quid est cur verear ne ad eam non ",
    "possim accommodare Torquatos nostros? Quos tu paulo ante cum memoriter, tum etiam erga nos ",
    "amice et benivole collegisti, nec me tamen laudandis maioribus meis corrupisti nec segniorem ",
    "ad respondendum reddidisti. Quorum facta quem ad modum, quaeso, interpretaris? Sicine eos ",
    "censes aut in armatum hostem impetum fecisse aut in liberos atque in sanguinem suum tam ",
    "crudelis fuisse, nihil ut de utilitatibus, nihil ut de commodis suis cogitarent? At id ne ",
    "ferae quidem faciunt, ut ita ruant itaque turbent, ut earum motus et impetus quo pertineant ",
    "non intellegamus, tu tam egregios viros censes tantas res gessisse sine causa? Quae fuerit ",
    "causa, mox videro; interea hoc tenebo, si ob aliquam causam istius, quae sine dubio ",
    "praeclara fuit, sapientes fecerunt, virtutem ipsam causam non fuisse.",
).as_bytes();
